"""align_database_schema

Revision ID: 27bf1154c14b
Revises: 4eb94ef6a0e0
Create Date: 2026-06-23 10:54:35.623261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27bf1154c14b'
down_revision: Union[str, None] = '4eb94ef6a0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('dataset_metadata',
    sa.Column('metadata_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('dataset_name', sa.String(length=500), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=True),
    sa.Column('dataset_type', sa.String(length=50), nullable=True),
    sa.Column('study_type', sa.String(length=100), nullable=True),
    sa.Column('target_population', sa.String(), nullable=True),
    sa.Column('geographic_coverage', sa.String(length=255), nullable=True),
    sa.Column('age_range_min', sa.Integer(), nullable=True),
    sa.Column('age_range_max', sa.Integer(), nullable=True),
    sa.Column('sex_distribution', sa.String(length=50), nullable=True),
    sa.Column('num_sites', sa.Integer(), nullable=True),
    sa.Column('collection_start_date', sa.Date(), nullable=True),
    sa.Column('collection_end_date', sa.Date(), nullable=True),
    sa.Column('annotation_methodology', sa.String(), nullable=True),
    sa.Column('num_annotators', sa.Integer(), nullable=True),
    sa.Column('irr_method', sa.String(length=100), nullable=True),
    sa.Column('irr_value', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('standards_used', sa.String(length=255), nullable=True),
    sa.Column('ethics_approval_ref', sa.String(length=255), nullable=True),
    sa.Column('consent_type', sa.String(length=100), nullable=True),
    sa.Column('deidentification_method', sa.String(length=255), nullable=True),
    sa.Column('differential_privacy_applied', sa.Boolean(), nullable=True),
    sa.Column('dp_epsilon', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sensitivity_class', sa.Enum('standard', 'high_stigma', 'critical', name='sensitivity_class'), nullable=False),
    sa.Column('persistent_identifier', sa.String(length=500), nullable=True),
    sa.Column('license_type', sa.String(length=100), nullable=True),
    sa.Column('synthetic_data_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('access_control_method', sa.String(length=255), nullable=True),
    sa.Column('linked_model_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_dictionary_uploaded', sa.Boolean(), nullable=True),
    sa.Column('provenance_pipeline_available', sa.Boolean(), nullable=True),
    sa.Column('github_repo_url', sa.String(length=500), nullable=True),
    sa.Column('changelog_provided', sa.Boolean(), nullable=True),
    sa.Column('version_format', sa.String(length=50), nullable=True),
    sa.Column('raw_form_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metadata_id')
    )
    op.create_index(op.f('ix_dataset_metadata_assessment_id'), 'dataset_metadata', ['assessment_id'], unique=False)
    op.create_table('dataset_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profiled_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('profiler_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_dataset_profiles_assessment_id'), 'dataset_profiles', ['assessment_id'], unique=False)
    op.add_column('assessment_results', sa.Column('total_domain_score', sa.Integer(), nullable=False))
    op.add_column('assessment_results', sa.Column('max_possible_score', sa.Integer(), nullable=False))
    op.add_column('assessment_results', sa.Column('cqi_formula_trace', sa.String(length=100), nullable=True))
    op.add_column('assessment_results', sa.Column('prs_baseline_risk', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('assessment_results', sa.Column('prs_sensitivity_multiplier', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('assessment_results', sa.Column('prs_computation_trace', sa.String(), nullable=True))
    op.add_column('assessment_results', sa.Column('policy_override_applied', sa.Boolean(), nullable=False))
    op.add_column('assessment_results', sa.Column('report_json_url', sa.String(length=500), nullable=True))
    op.add_column('assessment_results', sa.Column('report_html_url', sa.String(length=500), nullable=True))
    op.add_column('assessment_results', sa.Column('report_pdf_url', sa.String(length=500), nullable=True))
    op.add_column('assessment_results', sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('assessment_results', 'cqi',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=False)
    op.alter_column('assessment_results', 'classification_justification',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_assessment_results_assessment_id', table_name='assessment_results')
    op.create_index(op.f('ix_assessment_results_assessment_id'), 'assessment_results', ['assessment_id'], unique=True)
    op.drop_column('assessment_results', 'report_urls')
    op.drop_column('assessment_results', 'profile_summary')
    op.add_column('assessments', sa.Column('submitter_id', sa.String(length=255), nullable=True))
    op.add_column('assessments', sa.Column('submission_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('assessments', sa.Column('completion_timestamp', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('assessments', sa.Column('assessment_mode', sa.String(length=20), nullable=False))
    op.add_column('assessments', sa.Column('file_format', sa.String(length=50), nullable=True))
    op.add_column('assessments', sa.Column('file_size_bytes', sa.BIGINT(), nullable=True))
    op.add_column('assessments', sa.Column('file_sha256', sa.String(length=64), nullable=True))
    op.add_column('assessments', sa.Column('s3_file_key', sa.String(length=500), nullable=True))
    op.add_column('assessments', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.add_column('assessments', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('assessments', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('assessments', 'dataset_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_index(op.f('ix_assessments_submission_timestamp'), 'assessments', ['submission_timestamp'], unique=False)
    op.drop_column('assessments', 'completed_at')
    op.drop_column('assessments', 'submitted_at')
    op.drop_column('assessments', 'started_at')
    op.alter_column('audit_logs', 'event_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('audit_logs', 'severity',
               existing_type=postgresql.ENUM('INFO', 'WARNING', 'ERROR', name='severity_level'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_logs_event_timestamp'), 'audit_logs', ['event_timestamp'], unique=False)
    op.add_column('domain_scores', sa.Column('data_signals_count', sa.Integer(), nullable=True))
    op.add_column('domain_scores', sa.Column('meta_signals_count', sa.Integer(), nullable=True))
    op.add_column('domain_scores', sa.Column('scored_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('domain_scores', 'max_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_scores', sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('domain_scores', 'scored_at')
    op.drop_column('domain_scores', 'meta_signals_count')
    op.drop_column('domain_scores', 'data_signals_count')
    op.drop_index(op.f('ix_audit_logs_event_timestamp'), table_name='audit_logs')
    op.alter_column('audit_logs', 'severity',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('INFO', 'WARNING', 'ERROR', name='severity_level'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'event_timestamp',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('assessments', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('assessments', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_assessments_submission_timestamp'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.alter_column('assessments', 'dataset_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('assessments', 'updated_at')
    op.drop_column('assessments', 'created_at')
    op.drop_column('assessments', 'celery_task_id')
    op.drop_column('assessments', 's3_file_key')
    op.drop_column('assessments', 'file_sha256')
    op.drop_column('assessments', 'file_size_bytes')
    op.drop_column('assessments', 'file_format')
    op.drop_column('assessments', 'assessment_mode')
    op.drop_column('assessments', 'completion_timestamp')
    op.drop_column('assessments', 'submission_timestamp')
    op.drop_column('assessments', 'submitter_id')
    op.add_column('assessment_results', sa.Column('profile_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('assessment_results', sa.Column('report_urls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_assessment_results_assessment_id'), table_name='assessment_results')
    op.create_index('ix_assessment_results_assessment_id', 'assessment_results', ['assessment_id'], unique=False)
    op.alter_column('assessment_results', 'classification_justification',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assessment_results', 'cqi',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.NUMERIC(precision=4, scale=1),
               existing_nullable=False)
    op.drop_column('assessment_results', 'computed_at')
    op.drop_column('assessment_results', 'report_pdf_url')
    op.drop_column('assessment_results', 'report_html_url')
    op.drop_column('assessment_results', 'report_json_url')
    op.drop_column('assessment_results', 'policy_override_applied')
    op.drop_column('assessment_results', 'prs_computation_trace')
    op.drop_column('assessment_results', 'prs_sensitivity_multiplier')
    op.drop_column('assessment_results', 'prs_baseline_risk')
    op.drop_column('assessment_results', 'cqi_formula_trace')
    op.drop_column('assessment_results', 'max_possible_score')
    op.drop_column('assessment_results', 'total_domain_score')
    op.drop_index(op.f('ix_dataset_profiles_assessment_id'), table_name='dataset_profiles')
    op.drop_table('dataset_profiles')
    op.drop_index(op.f('ix_dataset_metadata_assessment_id'), table_name='dataset_metadata')
    op.drop_table('dataset_metadata')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
