"""add_server_defaults_and_extension

Revision ID: 66f8bf091d62
Revises: 746fb38e812d
Create Date: 2026-06-23 11:17:30.573675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f8bf091d62'
down_revision: Union[str, None] = '746fb38e812d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable extension
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

    op.drop_index('idx_assessment_results_cqi', table_name='assessment_results')
    op.create_index('idx_assessment_results_cqi', 'assessment_results', [sa.text('cqi DESC')], unique=False)
    
    # Primary Key server defaults
    op.alter_column('assessments', 'assessment_id', server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('dataset_metadata', 'metadata_id', server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('dataset_profiles', 'profile_id', server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('domain_scores', 'score_id', server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('assessment_results', 'result_id', server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('audit_logs', 'log_id', server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('api_keys', 'key_id', server_default=sa.text('uuid_generate_v4()'))

    # Column server defaults
    op.alter_column('assessments', 'status', server_default=sa.text("'queued'"))
    op.alter_column('assessments', 'toolkit_version', server_default=sa.text("'1.0.0'"))
    op.alter_column('assessments', 'domain_11_applicable', server_default=sa.text('true'))
    op.alter_column('assessments', 'assessment_mode', server_default=sa.text("'full'"))

    op.alter_column('dataset_metadata', 'differential_privacy_applied', server_default=sa.text('false'))
    op.alter_column('dataset_metadata', 'sensitivity_class', server_default=sa.text("'standard'"))
    op.alter_column('dataset_metadata', 'data_dictionary_uploaded', server_default=sa.text('false'))
    op.alter_column('dataset_metadata', 'provenance_pipeline_available', server_default=sa.text('false'))
    op.alter_column('dataset_metadata', 'changelog_provided', server_default=sa.text('false'))

    op.alter_column('dataset_profiles', 'profiler_version', server_default=sa.text("'1.0.0'"))

    op.alter_column('domain_scores', 'not_applicable', server_default=sa.text('false'))

    op.alter_column('assessment_results', 'policy_override_applied', server_default=sa.text('false'))

    op.alter_column('audit_logs', 'severity', server_default=sa.text("'INFO'"))

    op.alter_column('api_keys', 'role', server_default=sa.text("'submitter'"))
    op.alter_column('api_keys', 'is_active', server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop column server defaults
    op.alter_column('api_keys', 'is_active', server_default=None)
    op.alter_column('api_keys', 'role', server_default=None)

    op.alter_column('audit_logs', 'severity', server_default=None)

    op.alter_column('assessment_results', 'policy_override_applied', server_default=None)

    op.alter_column('domain_scores', 'not_applicable', server_default=None)

    op.alter_column('dataset_profiles', 'profiler_version', server_default=None)

    op.alter_column('dataset_metadata', 'changelog_provided', server_default=None)
    op.alter_column('dataset_metadata', 'provenance_pipeline_available', server_default=None)
    op.alter_column('dataset_metadata', 'data_dictionary_uploaded', server_default=None)
    op.alter_column('dataset_metadata', 'sensitivity_class', server_default=None)
    op.alter_column('dataset_metadata', 'differential_privacy_applied', server_default=None)

    op.alter_column('assessments', 'assessment_mode', server_default=None)
    op.alter_column('assessments', 'domain_11_applicable', server_default=None)
    op.alter_column('assessments', 'toolkit_version', server_default=None)
    op.alter_column('assessments', 'status', server_default=None)

    # Drop Primary Key server defaults
    op.alter_column('api_keys', 'key_id', server_default=None)
    op.alter_column('audit_logs', 'log_id', server_default=None)
    op.alter_column('assessment_results', 'result_id', server_default=None)
    op.alter_column('domain_scores', 'score_id', server_default=None)
    op.alter_column('dataset_profiles', 'profile_id', server_default=None)
    op.alter_column('dataset_metadata', 'metadata_id', server_default=None)
    op.alter_column('assessments', 'assessment_id', server_default=None)

    # Restore CQI index to ascending
    op.drop_index('idx_assessment_results_cqi', table_name='assessment_results')
    op.create_index('idx_assessment_results_cqi', 'assessment_results', ['cqi'], unique=False)

    # Drop extension
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp";')
    # ### end Alembic commands ###
