"""add_missing_constraints_and_indexes

Revision ID: 746fb38e812d
Revises: 27bf1154c14b
Create Date: 2026-06-23 11:09:24.421908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746fb38e812d'
down_revision: Union[str, None] = '27bf1154c14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_assessment_results_cqi', 'assessment_results', ['cqi'], unique=False)
    op.create_index('idx_assessment_results_release_classification', 'assessment_results', ['release_classification'], unique=False)
    op.create_index('idx_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('idx_domain_scores_domain_number', 'domain_scores', ['domain_number'], unique=False)
    op.create_unique_constraint('uq_domain_scores_assessment_domain', 'domain_scores', ['assessment_id', 'domain_number'])
    
    # Custom CHECK constraints
    op.create_check_constraint('chk_domain_scores_domain_number', 'domain_scores', 'domain_number >= 1 AND domain_number <= 15')
    op.create_check_constraint('chk_domain_scores_score', 'domain_scores', 'score >= 0 AND score <= 4')
    op.create_check_constraint('chk_assessment_results_prs', 'assessment_results', 'prs >= 0 AND prs <= 100')
    
    # Custom PostgreSQL rule for append-only audit_logs
    op.execute("CREATE RULE no_delete_audit AS ON DELETE TO audit_logs DO INSTEAD NOTHING;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom PostgreSQL rule downgrade
    op.execute("DROP RULE IF EXISTS no_delete_audit ON audit_logs;")
    
    # Custom CHECK constraints downgrade
    op.drop_constraint('chk_assessment_results_prs', 'assessment_results', type_='check')
    op.drop_constraint('chk_domain_scores_score', 'domain_scores', type_='check')
    op.drop_constraint('chk_domain_scores_domain_number', 'domain_scores', type_='check')
    
    op.drop_constraint('uq_domain_scores_assessment_domain', 'domain_scores', type_='unique')
    op.drop_index('idx_domain_scores_domain_number', table_name='domain_scores')
    op.drop_index('idx_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('idx_assessment_results_release_classification', table_name='assessment_results')
    op.drop_index('idx_assessment_results_cqi', table_name='assessment_results')
    # ### end Alembic commands ###
