"""add_sustainability_and_feedback_columns

Revision ID: 890e049e50b2
Revises: b2c3d4e5f6a7
Create Date: 2026-07-01 14:02:01.783181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890e049e50b2'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_metadata', sa.Column('sustainability_info_provided', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('dataset_metadata', sa.Column('feedback_mechanism_exists', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_metadata', 'feedback_mechanism_exists')
    op.drop_column('dataset_metadata', 'sustainability_info_provided')
    # ### end Alembic commands ###
